version: '3'
services:
    #Postgres database
    postgres-db:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    #API server
    api:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        image: supriyaibm/simple_blog__api
        environment:
            - POSTGRES_HOST=postgres-db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_DB=simple_blog_api
            - POSTGRES_PASSWORD=postgres_password
        ports:
            - "3000:3000"